---
title: "comparison_models"
author: "Jing"
date: "2024-10-17"
output: html_document
Context: Normalization of satellite-resolution LU500 variables are realized using standard QT.
 

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(dplyr)
library(mgcv)
library(ggplot2)
library(nlme)
library(fitdistrplus)
library(bestNormalize)
library(visreg)
library(lmerTest)
library(corrplot)
library(sjPlot)
library(gratia) 
library(patchwork)
library(preprocessCore)
colnames(hundred_df)
```


```{r 100m buffer general models}
dom_landcover <- read.csv('/Users/lidiayung/Downloads/PhyChe_XY_landcover(in).csv')
dom_landcover


hundred_df <- read.csv('/Users/lidiayung/PhD_project/project_PONDERFUL/ponderful_OUTPUT/Phy_Che_oct_qt.csv')


##Country as factors
hundred_df$Country <- as.factor(hundred_df$Country)
levels(hundred_df$Country)

hist(hundred_df$Hydeoperiod_length)
##Alternative categories
## Bio climatic regions
hundred_df$altregion <- 'Atlantic'
table(hundred_df$Country)
hundred_df[hundred_df$Country == 'Spain' | hundred_df$Country == 'Turkey', "altregion"] <- 'Mediterranean'
hundred_df[hundred_df$Country == 'Belgium' | hundred_df$Country == 'Germany'
           | hundred_df$Country == 'Switzerland', "altregion"] <- 'centralEU'
hundred_df[hundred_df$Country == 'Uruguay',]$altregion <- 'Uruguay'

##Factors and transformation 
hundred_df$Country <- as.factor(hundred_df$Country)
levels(hundred_df$Country)
View(hundred_df)
hundred_df$altregion <- as.factor(hundred_df$altregion)
levels(hundred_df$altregion)

hist(hundred_df$Area.t)

hundred_df$log_TN <- log(hundred_df$TN,base=10)
hist(hundred_df$log_TN)
shapiro.test(hundred_df$log_TN)


hundred_df$log_TP <- log(hundred_df$TP,base=10)
hist(hundred_df$log_TP)
shapiro.test(hundred_df$log_TP)


# Check which columns contain NA values
na_columns <- sapply(hundred_df_standardized, function(x) any(is.na(x)))

# Display the names of columns that contain NA values
columns_with_na <- names(hundred_df_standardized)[na_columns]
columns_with_na


hist(hundred_df_standardized$TN,main='Distribution of Response Variable TN(n=238)',xlab = 'TN')
hist(hundred_df_standardized$TP,main='Distribution of Response Variable TP',xlab = 'TP')

#Fish var 0.5 means that in two consecutive years there was a 0 and a 1
hundred_df$Fish[hundred_df$Fish == 0.5] <- 1

hist(hundred_df$Fish)

          
```

```{r Standarization}
#LU variables standerized already. Method used is as follow
# transformar_columna <- function(x) {
#   perc <- rank(x, na.last = "keep") / (sum(!is.na(x)) + 1)  # Calcular los percentiles manteniendo los NA
#   result <- ifelse(!is.na(x), qnorm(perc), NA)  # Transformar los percentiles a la distribución normal, manteniendo los NA
#   return(result)


#'bio1.t','bio7.t','bio5.t','bio12.t','Hydeoperiod_length.t','Fish','Animals_cont.t'

hundred_df[,c('bio1.s','bio7.s','bio5.s','bio12.s','Hydeoperiod_length.s','Animals_cont.s','Area.s')] <-scale(hundred_df[,c('bio1.t','bio7.t','bio5.t','bio12.t','Hydeoperiod_length.t','Animals_cont.t','Area.t')], center = TRUE, scale = TRUE)

hist(hundred_df$Pastures.and.open.nature_500.t)
```

```{r excluding uru df}

input <- 'Uruguay'
df <- hundred_df[hundred_df$altregion != input,]
model_df <- df[,c('log_TP','TP','TN','log_TN','Natural_5.t','Cropland_500.t',
                  'Pastures.and.open.nature_500.t','Hydeoperiod_length.s',
                  'Area.s','Animals_cont.s','Forest_500.t','Urban_500.t','Aquatic_500.t',
                  'Natural_5_qt', 'Aquatic_500_qt', 'Cropland_500_qt','Forest_500_qt',
                            'Pastures.and.open.nature_500_qt',
                             'Urban_500_qt',
                    'bio1.s','bio7.s','bio5.s','bio12.s','Depth.t','Fish')]
model_df <-na.omit(model_df)

corrplot(cor(model_df[,c( 'Natural_5.t','Cropland_500.t', 'Pastures.and.open.nature_500.t', 'Area.s','Animals_cont.s','Hydeoperiod_length.s',
                    'bio1.s','bio7.s','bio5.s','bio12.s')]),order='alphabet',type='upper',tl.col='black',tl.srt = 45,main='Full')



round(cor(model_df[,c( 'Natural_5.t','Cropland_500.t', 'Pastures.and.open.nature_500.t', 'Area.s','Animals_cont.s',
                    'bio1.s','bio7.s','bio5.s','bio12.s')]),2)

```

```{r TP models}
TP_exc_linear_model <- glm(TP ~ Natural_5.t+Cropland_500.t + Pastures.and.open.nature_500.t + 
                             Animals_cont.s + Depth.t + bio1.s+Fish+Hydeoperiod_length.s, family = Gamma(link = "log"), 
                           data = model_df)

summary(TP_exc_linear_model)
step(TP_exc_linear_model)

TP_exc_linear_model_selected <-  glm(formula = TP ~ Natural_5.t + Cropland_500.t + Pastures.and.open.nature_500.t + 
    Animals_cont.s + Depth.t + bio1.s, family = Gamma(link = "log"), 
    data = model_df)

summary(TP_exc_linear_model_selected)
tab_model(TP_exc_linear_model_selected)

plots <- visreg(TP_exc_linear_model_selected,gg=TRUE)
combined_plot <- wrap_plots(plots)
combined_plot

diagnostic_plots <- appraise(TP_exc_linear_model_selected)
diagnostic_plots

dev_resid <- residuals(TP_exc_linear_model_selected,type="deviance")
shapiro.test(dev_resid)


test <- glm(log_TP ~   Natural_5.t+Cropland_500.t + Pastures.and.open.nature_500.t + 
                             Animals_cont.s + Depth.t + bio1.s+Fish+Hydeoperiod_length.s, 
                           data = model_df)

summary(test)
step(test)
tab_model(test)

dev_resid <- residuals(test,type="deviance")
shapiro.test(dev_resid)

test_selected <- glm(formula = log_TP ~ Natural_5.t + Cropland_500.t + Pastures.and.open.nature_500.t + 
    Animals_cont.s + Depth.t + bio1.s + Fish, data = model_df)
summary(test_selected)
tab_model(test_selected)

dev_resid <- residuals(test_selected,type="deviance")
shapiro.test(dev_resid)

#qt
TP_exc_linear_model <-glm(formula = TP ~ Natural_5_qt+Cropland_500_qt + Pastures.and.open.nature_500_qt + 
    Animals_cont.s + Depth.t + bio1.s+Fish+Hydeoperiod_length.s, family = Gamma(link = "log"), 
    data = model_df)

summary(TP_exc_linear_model)
step(TP_exc_linear_model)


TP_exc_linear_model_selected_qt <-glm(formula = TP ~ Cropland_500_qt + Pastures.and.open.nature_500_qt + 
    Animals_cont.s + Depth.t + bio1.s, family = Gamma(link = "log"), 
    data = model_df)

summary(TP_exc_linear_model_selected_qt)
tab_model(TP_exc_linear_model_selected_qt)


plots <- visreg(TP_exc_linear_model_selected_qt,gg=TRUE)
combined_plot <- wrap_plots(plots)
combined_plot

diagnostic_plots <- appraise(TP_exc_linear_model_selected_qt)
diagnostic_plots
```
```{r TN}
TN_exc_linear_model <- glm(log_TN ~ Natural_5.t + Aquatic_500.t + Cropland_500.t +
                            Pastures.and.open.nature_500.t +
                             Urban_500.t + Animals_cont.s + Area.s + Depth.t +
                             bio1.s+bio7.s+Fish+Hydeoperiod_length.s, 
                           data = model_df)

hist(model_df$Hydeoperiod_length.s)


summary(TN_exc_linear_model)
step(TN_exc_linear_model)


TN_exc_linear_model_selected <-  glm(formula = log_TN ~ Natural_5.t + Cropland_500.t + Animals_cont.s + 
    Area.s + Depth.t + bio7.s + Fish, data = model_df)

summary(TN_exc_linear_model_selected)
tab_model(TN_exc_linear_model_selected)

plots <- visreg(TN_exc_linear_model_selected,gg=TRUE)
combined_plot <- wrap_plots(plots)
combined_plot

diagnostic_plots <- appraise(TN_exc_linear_model_selected)
diagnostic_plots

dev_resid <- residuals(TN_exc_linear_model_selected,type="deviance")
shapiro.test(dev_resid)



dev_resid <- residuals(test,type="deviance")
shapiro.test(dev_resid)

test_selected <- glm(formula = log_TP ~ Natural_5.t + Cropland_500.t + Pastures.and.open.nature_500.t + 
    Animals_cont.s + Depth.t + bio1.s + Fish, data = model_df)
summary(test_selected)
tab_model(test_selected)

dev_resid <- residuals(test_selected,type="deviance")
shapiro.test(dev_resid)

#qt
TN_exc_linear_model_selected <-glm(log_TN ~ Natural_5_qt + Aquatic_500_qt + Cropland_500_qt +
                            Pastures.and.open.nature_500_qt +
                             Urban_500_qt + Animals_cont.s + Area.s + Depth.t +
                             bio1.s+bio7.s+Fish+Hydeoperiod_length.s, 
                           data = model_df)


summary(TN_exc_linear_model_selected)
step(TN_exc_linear_model_selected)


TN_exc_linear_model_selected_qt <-glm(formula = log_TN ~ Natural_5_qt + Cropland_500_qt + Animals_cont.s + 
    Area.s + Depth.t + bio7.s + Fish, data = model_df)

summary(TN_exc_linear_model_selected_qt)
tab_model(TN_exc_linear_model_selected_qt)


plots <- visreg(TN_exc_linear_model_selected_qt,gg=TRUE)
combined_plot <- wrap_plots(plots)
combined_plot

diagnostic_plots <- appraise(TN_exc_linear_model_selected_qt)
diagnostic_plots


dev_resid <- residuals(TN_exc_linear_model_selected_qt,type="deviance")
shapiro.test(dev_resid)

```

