---
title: "Ponderful 100m"
author: "Jing"
date: "2024-10-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(dplyr)
library(mgcv)
library(ggplot2)
library(nlme)
library(fitdistrplus)
library(bestNormalize)
library(visreg)
library(lmerTest)
library(corrplot)
library(sjPlot)
library(gratia) 
library(patchwork)
library(preprocessCore)
colnames(hundred_df)
```

#Prep

```{r 100m buffer general models}
dom_landcover <- read.csv('/Users/lidiayung/Downloads/PhyChe_XY_landcover(in).csv')
dom_landcover
lu_100.t <- normalize.quantiles(as.matrix(hundred_df[,c('Arable_imp_grass','Forest_100','Pasture_Open_nature_100','Other_100')])
)
View(lu_100.t)

transformar_columna <- function(x) {
  perc <- rank(x, na.last = "keep") / (sum(!is.na(x)) + 1)  # Calcular los percentiles manteniendo los NA
  result <- ifelse(!is.na(x), qnorm(perc), NA)  # Transformar los percentiles a la distribución normal, manteniendo los NA
  return(result)
}

check <- as.data.frame(apply(hundred_df[,c('Cropland_500','Aquatic_500','Forest_500','Urban_500')], 2, transformar_columna))

check <- as.data.frame(apply(phy_che[, c('Cropland_500', 'Aquatic_500', 'Forest_500', 'Urban_500')], 2, transformar_columna))

combined_df <- cbind(phy_che[, c('Cropland_500', 'Aquatic_500', 'Forest_500', 'Urban_500')], check)
View(hundred_df[, c('Cropland_500', 'Aquatic_500')])

View(combined_df)


hundred_df[,c('Cropland_500','Aquatic_500','Forest_500','Urban_500')]
hist(check$Arable_imp_grass)

lu_500.t <- normalize.quantiles(as.matrix(hundred_df[,c('Cropland_500','Aquatic_500','Forest_500','Urban_500')])
)

View(phy_che[,c('Cropland_500','Aquatic_500','Forest_500','Urban_500')])
#df with transformed vars
hundred_df <- read.csv('/Users/lidiayung/PhD_project/project_PONDERFUL/ponderful_OUTPUT/Phy_Che_oct_qt.csv')

##Country as factors
hundred_df$Country <- as.factor(hundred_df$Country)
levels(hundred_df$Country)

hist(hundred_df$Hydeoperiod_length)
##Alternative categories
## Bio climatic regions
hundred_df$altregion <- 'Atlantic'

hundred_df[hundred_df$Country == 'Spain' | hundred_df$Country == 'Turkey', "altregion"] <- 'Mediterranean'
hundred_df[hundred_df$Country == 'Belgium' | hundred_df$Country == 'Germany', "altregion"] <- 'BelGE'
hundred_df[hundred_df$Country == 'Uruguay',]$altregion <- 'Uruguay'
hundred_df[hundred_df$Country == 'Switzerland',]$altregion <- 'Switzerland'

##Factors and transformation 
hundred_df$Country <- as.factor(hundred_df$Country)
levels(hundred_df$Country)
View(hundred_df)
hundred_df$altregion <- as.factor(hundred_df$altregion)
levels(hundred_df$altregion)

hundred_df_standardized <- hundred_df %>%
  mutate(across(c(Natural_5_qt,Arable_100_qt, Imp_grassland_100_qt, 
                  Forest_100_qt, Pastures.and.open.nature_100_qt, 
                  Animals_cont.t, Area.t, Depth.t, 
                  Aquatic_500_qt, Cropland_500_qt,
                  Forest_500_qt, Pastures.and.open.nature_500_qt,
                  Urban_500_qt,Natural_5.t,
                  #Arable_100.t, Imp_grassland_100.t, 
                  #Forest_100.t, Pastures.and.open.nature_100.t, 
                  Aquatic_500.t, Cropland_500.t,
                  Forest_500_qt, Pastures.and.open.nature_500.t,
                  Urban_500.t,
                  bio1.t,bio4.t,bio5.t,
                  bio6.t,bio7.t,
                  bio12.t,bio15.t,bio17.t), 
                ~ scale(.)[, 1]))


hundred_df_standardized$log_TN <- log(hundred_df_standardized$TN,base=10)
hist(hundred_df_standardized$log_TN)
shapiro.test(hundred_df_standardized$log_TN)

# Check which columns contain NA values
na_columns <- sapply(hundred_df_standardized, function(x) any(is.na(x)))

# Display the names of columns that contain NA values
columns_with_na <- names(hundred_df_standardized)[na_columns]
columns_with_na


hist(hundred_df_standardized$TN,main='Distribution of Response Variable TN(n=238)',xlab = 'TN')
hist(hundred_df_standardized$TP,main='Distribution of Response Variable TP',xlab = 'TP')

#Fish var 0.5 means that in two consecutive years there was a 0 and a 1
hundred_df_standardized$Fish[hundred_df_standardized$Fish == 0.5] <- 1

hist(hundred_df_standardized$Fish)

table(hundred_df$Fish)
```

```{r model df}
model_df <- hundred_df_standardized[,c('PondCode','log_TN','TN','TP','Natural_5_qt','Arable_100_qt','Imp_grassland_100_qt',
                                          'Depth.t','Forest_100_qt','Area.t','Pastures.and.open.nature_100_qt','Arable_imp_grass_100_qt','Hydeoperiod_length','Hydeoperiod_length.t',
                                        'Animals_cont.t','bio1.t','bio7.t','bio5.t','bio12.t','altregion','bio7','Fish','X','Y','Arable_100','Natural_5_qt', 'Aquatic_500_qt',
                                                     'Cropland_500_qt', 'Natural_5',
                                                     'Forest_500_qt', 'Pastures.and.open.nature_500_qt',
                                                     'Urban_500_qt','Aquatic_500.t', 'Cropland_500.t',
                  'Forest_500_qt', 'Pastures.and.open.nature_500.t',
                  'Urban_500.t', "Natural_5.t"
                                          )]


corrplot(cor(df[,c( 'Natural_5_qt','Arable_100_qt', 'Arable_100','Imp_grassland_100_qt','Arable_imp_grass_100_qt',
                                                'Depth.t','Forest_100_qt','Area.t','Pastures.and.open.nature_100_qt',
                                                'Animals_cont.t','Fish',
                            'bio1.t','bio7.t','bio5.t','bio12.t')]),
         order='alphabet',type='upper',tl.col='black',tl.srt = 45,main='Full')

round(cor(model_df[,c( 'Natural_5_qt','Arable_100_qt', 'Arable_100','Imp_grassland_100_qt','Arable_imp_grass_100_qt',
                                                'Depth.t','Forest_100_qt','Area.t','Pastures.and.open.nature_100_qt',
                                                'Animals_cont.t','Fish',
                            'bio1.t','bio7.t','bio5.t','bio12.t')]),2)
```

#PCA on countries excluding Uruguay
```{r PCA on Euro Medi}
library(factoextra)
PCA_vars <- c('Arable_100_qt','Imp_grassland_100_qt','Forest_100_qt','Pastures.and.open.nature_100_qt')

input <- 'Uruguay'
df <- model_df[model_df$altregion != input,]
dim(model_df[model_df$altregion != input,])
data_normalized <- df[,PCA_vars]

data_normalized <- na.omit(data_normalized)

data.pca <- princomp(data_normalized)
summary(data.pca)

data.pca$loadings[, 1:4]

fviz_eig(data.pca, addlabels = TRUE)
# Graph of the variables
fviz_pca_var(data.pca, col.var = "black")

fviz_cos2(data.pca, choice = "var", axes = 1:2)

fviz_pca_var(data.pca, col.var = "cos2",
             gradient.cols = c("black", "orange", "green"),
             repel = TRUE)

#Retrieve first 2 components
df['lu100_PC1']<- data.pca$scores[, 1]
df['lu100_PC2']<- data.pca$scores[, 2]
```

#General models excluding Uruguay

```{r TP Full model excluding Uru}
test <- subset(hundred_df,is.na(Fish))

TP_all_hund_linear_model <- glm(TP ~ Natural_5_qt  + Arable_imp_grass_100_qt +
                         Forest_100_qt + Pastures.and.open.nature_100_qt +
                          Animals_cont.t + Area.t + Depth.t + Fish+
                         bio1.t + bio7.t, family=Gamma(link='log'),data = df)
summary(TP_all_hund_linear_model)
stepAIC(TP_all_hund_linear_model)

TP_all_hund_linear_model_selected <- glm(formula = TP ~ Forest_100_qt + Animals_cont.t + Depth.t + 
    Fish + bio1.t, family = Gamma(link = "log"), data = df)

summary(TP_all_hund_linear_model_selected)
tab_model(
  TP_all_hund_linear_model_selected, 
  show.intercept = TRUE, 
  transform = NULL)

plots <- visreg(TP_all_hund_linear_model_selected,gg=TRUE)
combined_plot <- wrap_plots(plots)
combined_plot

#PCs

df$Hydeoperiod_length
TP_all_pc_hund_linear_model <- glm(TP ~  lu100_PC1+lu100_PC2+
                          Animals_cont.t + Area.t + Depth.t + Fish+Hydeoperiod_length.t+
                         bio1.t + bio7.t, family=Gamma(link='log'),data = df)
summary(TP_all_pc_hund_linear_model)
step(TP_all_pc_hund_linear_model)
TP_all_pc_hund_linear_model_selected <- glm(formula = TP ~ lu100_PC2 + Animals_cont.t + Depth.t + Fish + 
    bio1.t, family = Gamma(link = "log"), data = df)

summary(TP_all_pc_hund_linear_model_selected)
tab_model(
  TP_all_pc_hund_linear_model_selected, 
  show.intercept = TRUE, 
  transform = NULL)
```

```{r TN Full model excluding Uru}
TN_all_hund_linear_model <- glm(log_TN ~ Natural_5_qt + Arable_imp_grass_100_qt +
                         Forest_100_qt + Pastures.and.open.nature_100_qt +
                          Animals_cont.t + Area.t + Depth.t + Fish+
                         bio1.t + bio7.t, data = df)
summary(TN_all_hund_linear_model)
stepAIC(TN_all_hund_linear_model)

TN_all_hund_linear_model_selected <- glm(formula = TN ~ Arable_imp_grass_100_qt + Forest_100_qt + 
    Animals_cont.t + Area.t + Depth.t, family = Gamma(link = "log"), 
    data = df)

summary(TN_all_hund_linear_model_selected
        )
test <- glm(formula = TN ~ Arable_100_qt + Forest_100_qt + Animals_cont.t + 
    Area.t + Depth.t + bio7.t, family = Gamma(link = "log"), 
    data = df)

AIC(test,TN_all_hund_linear_model_selected)
tab_model(
  TN_all_hund_linear_model_selected, 
  show.intercept = TRUE, 
  transform = NULL)


plots <- visreg(TN_all_hund_linear_model_selected,gg=TRUE)
combined_plot <- wrap_plots(plots)
combined_plot
  
# Check which columns contain NA values
na_columns <- sapply(df, function(x) any(is.na(x)))

# Display the names of columns that contain NA values
columns_with_na <- names(df)[na_columns]
columns_with_na


TN_all_pc_hund_linear_model <- glm(log_TN ~  lu100_PC1+lu100_PC2+
                          Animals_cont.t + Area.t + Depth.t + Fish+Hydeoperiod_length.t+
                         bio1.t + bio7.t, data = df)

summary(TN_all_pc_hund_linear_model)
df <-na.omit(df)
step(TN_all_pc_hund_linear_model)
TN_all_pc_hund_linear_model_selected <- glm(formula = log_TN ~ lu100_PC1 + lu100_PC2 + Animals_cont.t + 
    Area.t + Depth.t + Fish + bio7.t, data = df)


summary(TN_all_pc_hund_linear_model_selected)
tab_model(TN_all_pc_hund_linear_model_selected,show.intercept = TRUE, transform = NULL)

```

```{r}
library(spdep)

# Extracting residuals
residuals_glm <- residuals(TP_all_hund_linear_model_selected, type = "response")


# Create spatial coordinates
coords <- cbind(df$X, df$Y)

# Create a distance-based spatial weights matrix
# Here, we use k-nearest neighbors (e.g., k = 4)
nb <- knn2nb(knearneigh(coords, k = 4))

# Create a spatial weights list object
listw <- nb2listw(nb, style = "W")



```


```{r correlation}
library(nlme)
AnabaenaT1.exp <- glmmPQL(logit(AnabaenaAO) ~ (outdist + I(outdist^2)) * sampledepth , data = PT1, method = "ML",correlation = corExp(form = ~ long + lat, nugget=T),na.action=na.omit)


glmmPQL(formula = TP ~ Forest_100_qt + Animals_cont.t + Depth.t + 
    Fish + bio1.t, family = Gamma(link = "log"),data=df, correlation = corExp(form = ~ X + Y, nugget=T))



```

```{r 500m and fish}
TP_glm_500m <- glm(formula = TP ~ Natural_5_qt+Cropland_500_qt + Pastures.and.open.nature_500_qt + 
    Animals_cont.t + Depth.t + bio1.t+Fish+Hydeoperiod_length.t, family = Gamma(link = "log"), 
    data = df)


summary(TP_glm_500m)

stepAIC(TP_glm_500m)

selected <- glm(formula = TP ~ Cropland_500_qt + Pastures.and.open.nature_500_qt + 
    Animals_cont.t + Depth.t + bio1.t, family = Gamma(link = "log"), 
    data = df)
summary(selected)
tab_model(test_selected,show.intercept = TRUE,transform = NULL)
dev_resid <- residuals(selected,type="deviance")

shapiro.test(dev_resid)
#model with qt normalized model 
test <- glm(formula = TP ~ Natural_5.t+Cropland_500.t + Pastures.and.open.nature_500.t + 
    Animals_cont.t + Depth.t + bio1.t+Fish+Hydeoperiod_length.t, family = Gamma(link = "log"), 
    data = df)
summary(test)
step(test)
test_selected <- glm(formula = TP ~ Natural_5.t + Cropland_500.t + Pastures.and.open.nature_500.t + 
    Animals_cont.t + Depth.t + bio1.t, family = Gamma(link = "log"), 
    data = df)
summary(test_selected)

tab_model(test_selected)
deviance_value <- deviance(test_selected)
pearson_chi_sq <- sum(residuals(test_selected, type = "pearson")^2)

cat("Deviance:", deviance_value, "\n")
cat("Pearson Chi-square:", pearson_chi_sq, "\n")


#TN
test_TN <- glm(log_TN ~ Natural_5.t + Aquatic_500.t + Cropland_500.t +
                            Pastures.and.open.nature_500.t +
                             Urban_500.t + Animals_cont.t + Area.t + Depth.t +
                             bio1.t+bio7.t+Fish+Hydeoperiod_length.t, 
                           data = df)
summary(test_TN)
step(test_TN)

test_TN_selected <- glm(formula = log_TN ~ Natural_5.t + Cropland_500.t + Animals_cont.t + 
    Area.t + Depth.t + bio7.t + Fish, data = df)
summary(test_TN_selected)
dev_resid <- residuals(test_TN_selected,type="deviance")

shapiro.test(dev_resid)

tab_model(test_TN_selected,show.intercept = TRUE,transform = NULL)

TN_log_500m <- glm(log_TN ~ Natural_5_qt + Aquatic_500_qt + Cropland_500_qt +
                            Pastures.and.open.nature_500_qt +
                             Urban_500_qt + Animals_cont.t + Area.t + Depth.t +
                             bio1.t+bio7.t+Fish+Hydeoperiod_length.t, 
                           data = df)
summary(TN_log_500m)
step(TN_log_500m)

TN_log_500m_selected <-glm(formula = log_TN ~ Natural_5_qt + Cropland_500_qt + Animals_cont.t + 
    Area.t + Depth.t + bio7.t + Fish, data = df)
 
summary(TN_log_500m_selected) 
tab_model(TN_log_500m_selected,show.intercept = TRUE,transform=NULL)
```

#Models in alternative bioregions

```{r Atlantic}
input <- 'Atlantic'
df <- model_df[model_df$altregion == input,]


TN_atl_hund_linear_model <- glm(TN ~ Natural_5_qt + Arable_100_qt + Imp_grassland_100_qt +
                         Forest_100_qt + Pastures.and.open.nature_100_qt +
                          Animals_cont.t + Area.t + Depth.t + Fish+
                         bio1.t + bio7.t, family=Gamma(link='log'),data = df)
summary(TN_atl_hund_linear_model)
step(TN_atl_hund_linear_model)

TN_atl_hund_linear_model_selected <- glm(formula = TN ~ Pastures.and.open.nature_100_qt + Animals_cont.t + 
    bio1.t + bio7.t, family = Gamma(link = "log"), data = df)

summary(TN_atl_hund_linear_model_selected)
tab_model(
  TN_atl_hund_linear_model_selected, 
  show.intercept = TRUE, 
  transform = NULL)

plots <- visreg(TN_atl_hund_linear_model_selected,gg=TRUE)
combined_plot <- wrap_plots(plots)
combined_plot
```

















