---
title: "ponderful seasonility modelling"
author: "Jing"
date: "2025-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(corrplot)

```


```{r Input, echo=FALSE}
data_dir <- '/Users/lidiayung/PhD_project/project_PONDERFUL/ponderful_OUTPUT/ponderful_seasonility/'
model_df <- read.csv(paste0(data_dir,'hydrobiologia_seasonility_model.csv'))

model_df_valid <- model_df[!is.na(model_df$TP),] #769 records, 240 ponds  
table(model_df_valid$Country,model_df_valid$year)
```


```{r Prep, echo=FALSE}
#Factors
##Country as factors
model_df_valid$Country <- as.factor(model_df_valid$Country)
levels(model_df_valid$Country)


## Bio climatic regions
model_df_valid$Country <- as.character(model_df_valid$Country)

# Initialize altregion as a copy of Country
model_df_valid$altregion <- model_df_valid$Country

model_df_valid[model_df_valid$Country %in% c('Belgium', 'Denmark', 'UK'), "altregion"] <- 'Atlantic'
model_df_valid[model_df_valid$Country %in% c('Switzerland','Germany'), "altregion"] <- 'Temperate'

# Check the changes
table(model_df_valid$altregion)

##Factors and transformation 
model_df_valid$altregion <- as.factor(model_df_valid$altregion)
levels(model_df_valid$altregion)

#Adding log_TN (and log_TP)
model_df_valid$log_TN <- log(model_df_valid$TN,base=10)
hist(model_df_valid$log_TN)
shapiro.test(model_df_valid$log_TN)

model_df_valid$log_TP <- log(model_df_valid$TP,base=10)
hist(model_df_valid$log_TP)
shapiro.test(model_df_valid$log_TP)
```

```{r bestNormalize}
library(bestNormalize)

#Depth
shapiro.test(model_df_valid$Depth)
Depthn <- bestNormalize(model_df_valid$Depth)
plot(Depthn, leg_loc = "bottomright")
model_df_valid$Depth.t <- predict(orderNorm(model_df_valid$Depth))
hist(model_df_valid$Depth.t)
shapiro.test(model_df_valid$Depth.t)

#Animals_cont  skew
shapiro.test(model_df_valid$Animals_cont)
Animals_contn <- bestNormalize(model_df_valid$Animals_cont)
plot(Animals_contn, leg_loc = "bottomright")
model_df_valid$Animals_cont.t <- predict(orderNorm(model_df_valid$Animals_cont))
hist(model_df_valid$Animals_cont.t)
shapiro.test(model_df_valid$Animals_cont.t)

#MeanT
shapiro.test(model_df_valid$MeanT)
MeanT <- bestNormalize(model_df_valid$MeanT)
plot(MeanT, leg_loc = "bottomright")
model_df_valid$MeanT.t <- predict(orderNorm(model_df_valid$MeanT))
hist(model_df_valid$MeanT.t)
shapiro.test(model_df_valid$MeanT.t)

#sum_P
shapiro.test(model_df_valid$sum_P)
sum_P <- bestNormalize(model_df_valid$sum_P)
plot(sum_P, leg_loc = "bottomright")
model_df_valid$sum_P.t <- predict(orderNorm(model_df_valid$sum_P))
hist(model_df_valid$sum_P.t)
shapiro.test(model_df_valid$sum_P.t)

```

```{r Quantile transformation}
transformar_columna <- function(x) {
  perc <- rank(x, na.last = "keep") / (sum(!is.na(x)) + 1)  # Calcular los percentiles manteniendo los NA
  result <- ifelse(!is.na(x), qnorm(perc), NA)  # Transformar los percentiles a la distribución normal, manteniendo los NA
  return(result)}

#Natural_5, Aquatic_500,Cropland_500,Forest_500,Pastures.and.open.nature_500,Urban_500
model_df_valid$Natural_5.t<-transformar_columna(model_df_valid$Natural_5)
model_df_valid$Aquatic_500.t<-transformar_columna(model_df_valid$Aquatic_500)
model_df_valid$Cropland_500.t<-transformar_columna(model_df_valid$Cropland_500)
model_df_valid$Pastures.and.open.nature_500.t<-transformar_columna(model_df_valid$Pastures.and.open.nature_500)
model_df_valid$Urban_500.t<-transformar_columna(model_df_valid$Urban_500)
model_df_valid$Forest_500.t<-transformar_columna(model_df_valid$Forest_500)
model_df_valid$post_Emerse_pond.t<-transformar_columna(model_df_valid$post_Emerse_pond)
```

```{r Scale}
model_df_valid[,c('Animals_cont.s','Depth.s',"Aquatic_500.s",  
            "Cropland_500.s","Forest_500.s","Pastures.and.open.nature_500.s" ,
            "Urban_500.s", "Natural_5.s","MeanT.s","sum_P.s", "post_Emerse_pond.s")] <-scale(model_df_valid[,c(
                    'Animals_cont.t','Depth.t',"Aquatic_500.t",  
                    "Cropland_500.t","Forest_500.t","Pastures.and.open.nature_500.t" ,
                    "Urban_500.t", "Natural_5.t","MeanT.t","sum_P.t","post_Emerse_pond.t")], center = TRUE, scale = TRUE)

glmm_df <- model_df_valid[,c("Pond_ID" ,"PondCode","season_col"  ,"year","Country",
                             "Strat","Pond_dries","log_TN","log_TP",'Animals_cont.s','Depth.s',"Aquatic_500.s",
                             "Cropland_500.s","Forest_500.s","Pastures.and.open.nature_500.s" ,
                             "Urban_500.s", "Natural_5.s","MeanT.s","sum_P.s","post_Emerse_pond.s")]

write.csv(model_df_valid,paste0(data_dir,'ponderful_hydro_seasonality_glmm.csv'))
```

```{r Depth missing values}
length(unique(glmm_df$PondCode)) #240

#dealing with missing depth
glmm_df_depth_nonna <- glmm_df[!is.na(glmm_df$Depth.s),] #721 rows 
table(glmm_df_depth_nonna$Country)

setdiff(unique(model_df$PondCode),unique(glmm_df_depth_nonna$PondCode)) #239
unique(glmm_df[is.na(glmm_df$Depth.s),'PondCode'])
table(glmm_df[is.na(glmm_df$Depth.s),'Country'])

#other missing data
glmm_df_depth_nonna[!rownames(glmm_df_depth_nonna) %in% rownames(na.omit(glmm_df_depth_nonna)),]

#populate natural_5m, 
```

```{r populate natural col}
glmm_df_depth_nonna <- glmm_df_depth_nonna %>%
  group_by(PondCode, year, season_col) %>% 
  mutate(
    natural_5_filled.s = ifelse(is.na(Natural_5.s), 
                           ifelse(n_distinct(Natural_5.s[!is.na(Natural_5.s)]) == 1, unique(nature[!is.na(Natural_5.s)]), 
                                  ifelse(n_distinct(Natural_5.s[!is.na(Natural_5.s)]) > 1, 
                                         as.character(PondCode), NA)), 
                           Natural_5.s)
  ) %>%
  ungroup() %>%
  group_by(PondCode) %>%
  mutate(
    natural_5_filled.s = ifelse(is.na(natural_5_filled.s), 
                           ifelse(n_distinct(natural_5_filled.s[!is.na(natural_5_filled.s)]) == 1, unique(natural_5_filled.s[!is.na(natural_5_filled.s)]), 
                                  ifelse(n_distinct(natural_5_filled.s[!is.na(natural_5_filled.s)]) > 1, 
                                         as.character(PondCode), NA)), 
                           natural_5_filled.s)
  ) %>%
  ungroup()

# View result
print(glmm_df_depth_nonna)


glmm_df_depth_nonna[is.na(glmm_df_depth_nonna$natural_5_filled.s),]#missing SCL1 in both years 


#Get the table with non-missing values in depth and natural(populated)
glmm_df_depth_natural <- glmm_df_depth_nonna[!is.na(glmm_df_depth_nonna$natural_5_filled.s),]#718


glmm_df_depth_natural[is.na(glmm_df_depth_natural$Strat),]#36 
#check correlation
glmm_df_depth_natural_nonna <-  glmm_df_depth_natural[!is.na(glmm_df_depth_natural$Strat),] #682

write.csv(glmm_df_depth_natural_nonna, paste0(data_dir,'glmm_strata_natural_5_filleds.csv'))

```

